# Generated by Django 5.1.6 on 2025-04-17 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='puplished_date',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 18, 10, 33, 890329, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 18, 10, 33, 889661, tzinfo=datetime.timezone.utc)),
        ),
    ]
