# Generated by Django 4.2.11 on 2025-05-20 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 20, 23, 3, 32, 862568, tzinfo=datetime.timezone.utc)),
        ),
    ]
